Branch export
AY2324S2-CS2103T-T10-2/tp pull request #112
Opened 2024-04-03 18:52 UTC by SampsonYe1999

Export command is added.

Command Input format: "export"

A csv file named "patientData" will be automatically created under the "RapidTracerData" directory.
Only patient details are exported and stored in the csv file.

Resolves #97

2024-04-03 19:21 UTC, chengjunyuan requested changes
Would be good to delete the failing test cases

2024-04-04 05:21 UTC, legionlegion commented on docs/img.png
nice image

2024-04-04 05:21 UTC, legionlegion commented on src/test/java/seedu/address/logic/commands/ExportCommandTest.java
> +public class ExportCommandTest {
nice test cases!

2024-04-04 05:21 UTC, legionlegion commented on src/main/java/seedu/address/logic/commands/ExportCommand.java
> +    public JsonNode readJsonFile(File jsonFile) throws CommandException {
nice function

2024-04-04 05:21 UTC, legionlegion commented on docs/img_1.png
i like how you used fake phone numbers to protect my privacy!

2024-04-04 05:21 UTC, legionlegion commented on docs/UserGuide.md
> +  Importing patient data: "import"
good documentation!

2024-04-04 09:01 UTC, SampsonYe1999 commented
> Would be good to delete the failing test cases

Thank you for the suggestion. It worked after I removed the failed test cases and it's associated imports!

2024-04-04 09:17 UTC, chengjunyuan reviewed
LGTM. Can let either Min Rei or Shuyuan take a look before merging.

2024-04-04 10:21 UTC, legionlegion approved these changes
LGTM

2024-04-04 10:51 UTC, merged